# Generated by Django 5.0.2 on 2024-03-17 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0006_rename_expiry_jobpost_job_expiry_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobpost',
            old_name='Job_expiry_date',
            new_name='expiry',
        ),
    ]
