# Generated by Django 5.0.2 on 2024-03-18 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0009_author_jobpost_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='jobpost',
            name='skills',
            field=models.ManyToManyField(to='app_1.skills'),
        ),
    ]
